### ISSUE TITLE
Data file us-states.csv is not bundled

### ISSUE THREAD

**Issue by apatil** [jsilve24/ili_surge#1]
The code contains several reads of us-states.csv, but the file is not present in the repo and afaict is not generated by any code files.

**Comment by jsilve24** [comment]
Try now -- was just a broken sub-module. 

That data is just the New York Times COVID data. 

- https://github.com/nytimes/covid-19-data/tree/bf69d9d204e064caf31b53091b341053e97e8b09 <https://github.com/nytimes/covid-19-data/tree/bf69d9d204e064caf31b53091b341053e97e8b09>

Justin

**Comment by apatil** [comment]
Thanks, that worked. There are a few instances of the wrong path to that datafile, though, if you `git grep "data/covid-19-data/covid-19-data/us-states.csv"`.
